### ISSUE TITLE
Prevent skipping forward

### ISSUE THREAD

**Issue by kennberg** [tunapanda/h5p-standalone#103]
H5P has an option to prevent skipping forward (image).
![skipping](https://user-images.githubusercontent.com/1063561/139743401-aae3d61e-92ba-4878-b5df-5f69399f596e.png)

Looks like it's enabled via params.override.preventSkipping:
https://github.com/h5p/h5p-interactive-video/blob/master/src/scripts/interactive-video.js#L109

Is there a way to get this enabled via h5p standalone?

**Comment by mimidotsuser** [comment]
Hello @kennberg. This behavior is set while creating the content i.e. using the editor. You just have to select the checkbox under the `Behavioural settings` panel group.

![Screenshot from 2021-11-02 00-28-18](https://user-images.githubusercontent.com/25152892/139744485-c2719a87-026b-40fe-9ea9-3ffa856f00ef.png)

**Comment by kennberg** [comment]
Thank you.
