### ISSUE TITLE
customCss doesnt work please help

### ISSUE THREAD

**Issue by thejanz** [tunapanda/h5p-standalone#107]
Hey,

Nice Bundle!
everything works fine, except the customCss!

I have tried a lot but it wont work, maybe u see the issue and could help me :)

I cant find the Filename "h5pover.css" in the HTML-DOM (DEV-Tools)
There should be all relevant iformations in the Screenshot.

![image](https://user-images.githubusercontent.com/86104305/153963259-b7dc395e-fcf6-4fb0-8f21-ae6f3354bcf7.png)

**Comment by mimidotsuser** [comment]
Hello @thejanz. Custom styles or JavaScript are loaded asynchronously after the H5P player initializes. All H5P CSS and scripts links that should be loaded are injected into the H5P iframe `head` tag (during initialization). 
You can confirm that under the Chrome DevTools `network` tab section.
