### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by ishita-srivastava5** [tunapanda/h5p-standalone#109]

**Comment by DiegoGonzalezCruz** [comment]
@ishita-srivastava5  I know this is closed, but how did you manage to fix it? any ideas?

**Comment by 0xMurage** [comment]
I will add this here for reference purposes.

If you're encountering this error, it means you're attempting to run this package in a server-side environment, where the window object is not available. 

This package is designed to work **only** in a browser environment, as it relies on the presence of the window object, which is specific to client-side JavaScript execution.

 To resolve this, ensure that this package is only imported and executed on the browser side of your application.
