### ISSUE TITLE
Cant view content of h5p file

### ISSUE THREAD

**Issue by ishita-srivastava5** [tunapanda/h5p-standalone#110]
I can see the iframe is loaded and the h5p-container is populated, but i still cant see the content of the file. I am using react and next js. Any clue why i might not be able to see. I am not getting any errors. and i have unzipped my file as well. The body seems empty

**Comment by DiegoGonzalezCruz** [comment]
did you fix this?

**Comment by mimidotsuser** [comment]
feel free to reopen the issue if still experiencing the same issue (If so, include more info regarding the content of your H5P.)
