### ISSUE TITLE
Migration to Typescript 

### ISSUE THREAD

**Issue by murageyun** [tunapanda/h5p-standalone#113]
The project currently provides a baseline for anyone who wishes to have an H5P standalone player on their project via NPM. 
Although this works on most* occasions, developers utilizing Typescript would benefit more from types checking. There is a Typescript class file `h5p-standalone.class.ts` last updated in version 2.1.x. 

I am proposing migrating fully from loosely typed JavaScript to Typescript. The changes would require some code refactoring and updating the build pipeline to accommodate the changes. 
Another alternative would be providing the type annotations using a manually generated `.d.ts`.

@Jakeii and the core team, what do you think about my proposal? I am willing to assist in any way possible to ensure project stability and consistency.

**Comment by mimidotsuser** [comment]
@Jakeii I will work the migration process.
