### ISSUE TITLE
createH5P must be passed an element

### ISSUE THREAD

**Issue by assistenzamerqurio** [tunapanda/h5p-standalone#117]
Hi,

I have tried your project, when i call my html page, i have error "createH5P must be passed an element" on 
new H5PStandalone.H5P(el, options);

In attach my html file, what am i doing wrong?
[immagini.txt](https://github.com/tunapanda/h5p-standalone/files/8689161/immagini.txt)

**Comment by mimidotsuser** [comment]
your script is executed before the div is loaded into the DOM.

Easy and reliable fix is to execute the H5P logic once the DOM content is load i.e.

```javascript 
window.addEventListener('DOMContentLoaded',function(){

    const el = document.getElementById('h5p-container');
    const options = {
      h5pJsonPath:  '.',
      frameJs: './assets/frame.bundle.js',
      frameCss: './styles/h5p.css',
    }
  
    new H5PStandalone.H5P(el, options)

})
```

**Comment by assistenzamerqurio** [comment]
Hi,

Thank's. 
Now it's work fine!
