### ISSUE TITLE
Shared library to reduce redundancy for multiple workspaces

### ISSUE THREAD

**Issue by pheraph** [tunapanda/h5p-standalone#12]
Wouldn't it make sense to separate the actual content files (`workspace/content` and `workspace/h5p.json`) from the rest of the workspace libraries? If I place multiple h5p packages on the same server they could use a shared library with all the dependencies.

**Comment by mgancarzdsi** [comment]
Thinking about this, you would want to have the ability to have the different versions of the same h5p packages in this shared space. For example two h5p interactive videos, one created with Interactive Video 1.9.1 and another with 1.10.3

**Comment by Jakeii** [comment]
The workspace folder is for demo purposes only. You can point it at any folder with h5p content in it. And call it multiple times to have many on the same page.

```javascript
$('.h5p-container-1').h5p({
          frameJs: '../dist/js/h5p-standalone-frame.min.js',
          frameCss: '../dist/styles/h5p.css',
          h5pContent: './path/to/h5p/1'
        });

$('.h5p-container-2').h5p({
          frameJs: '../dist/js/h5p-standalone-frame.min.js',
          frameCss: '../dist/styles/h5p.css',
          h5pContent: '/path/to/h5p/2'
        });
```

**Comment by pheraph** [comment]
@mgancarzdsi Yes, that makes sense.

@Jakeii Thanks, yes, that's possible, but you still have full copies of all library files in both directories. Let's say I have 5 interactive videos each on a single html page. Every new page call loads all the javascript code again. If loaded from the same directory the browser could serve the files from the local cache. That's why I am suggesting to separate the individual content from the shared libraries.

**Comment by Jakeii** [comment]
I think that's an issue with H5P, all the content types are packaged with every h5p, each h5p is in it's own iframe, so all the libraries need to be loaded anyway.

**Comment by pheraph** [comment]
Then we are talking about a different approach. I think for my case where I don't have multiple iframes on a single page there is no need to store all libraries duplicated for each package. For example: why should I keep (and load!) FontAwesome (> 500kb) for every h5p package? This could be easily resolved if h5p standalone would separate package specific content from shared libraries. That's my point here.

**Comment by Jakeii** [comment]
It may be possible to have a library folder with a manifest that h5p-standalone would check for packages and load them from there.
But it would have to be manually filled with packages of all types and versions though.
Feel free to open a pull request!

**Comment by Bhavinder** [comment]
Hi 
Getting error after calling multiple times. Please suggest to resolve it.

TypeError: instance is undefined

$('.fillinblank').h5p({
  frameJs: 'js/h5p-standalone-frame.js', 
  frameCss: 'styles/h5p.css', 
  h5pContent: 'workspace/fill-in-the-blanks-837/'
});	  

$('.h5p-container').h5p({
  frameJs: 'js/h5p-standalone-frame.js', 
  frameCss: 'styles/h5p.css', 
  h5pContent: 'workspace/drag-the-words-1399/'
});

**Comment by Jakeii** [comment]
@Bhavinder you need to provide an `id`, and please create a new issue next time.

**Comment by tdxdave** [comment]
I am actually working on integrating standalone-h5p with a server process that will manage content/libraries. Basically I think having an optional libraryPath parameter to h5pStandalone class would do the trick. If you organize your libraries, we can use that instead of the content path. I'll work on a pull request.

**Comment by mimidotsuser** [comment]
issue fixed. Closing this.
