### ISSUE TITLE
H5p video can't display correct in Webview Android

### ISSUE THREAD

**Issue by tuyendev87** [tunapanda/h5p-standalone#120]
Hello
I am integrating h5p to display video on local server NanoHTTPD,
I downloaded and installed it according to the instructions at https://github.com/tunapanda/h5p-standalone -> Readme
I tried it on local apache server and it shows correctly, but when I try on android webview, it doesn't display properly.
It seems to be missing the .js or .css file for displaying interactive
Can you help me, if I am missing anything in the webview setup?

This is my code for Webview 
`   
private fun setupWebview() {
        val webView = findViewById<WebView>(R.id.webview)
        webView.apply {
            settings.apply {
                // enable Javascript
                javaScriptEnabled = true
                loadWithOverviewMode = true
                useWideViewPort = true
                domStorageEnabled = true
                allowContentAccess = true
                allowFileAccess = true
                allowFileAccessFromFileURLs = true
                allowUniversalAccessFromFileURLs = true
                pluginState = WebSettings.PluginState.ON
                mediaPlaybackRequiresUserGesture = false
            }
        }
        webView.webViewClient = CustomWebViewClient(this)
        webView.webChromeClient = CustomWebChromeClient(this)
        WebView.setWebContentsDebuggingEnabled(true);
        webView.loadDataWithBaseURL("http://localhost:8080", HTMLBuilder.getMainH5PPage(), "text/html", "UTF-8", "")
    }
`
I also add android:hardwareAccelerated="true" in application on manifest for warning html5.
this my h5p and video file: https://drive.google.com/file/d/1Pf0GWqBRnMz1llJoqGggUOYUahqPhpiR/view?usp=sharing
video in mobile: https://drive.google.com/file/d/1FVvRa7HX8lS4MjL_XXzsujczEIolqHhN/view?usp=sharing

**Comment by mimidotsuser** [comment]
@tuyendev87 did you identify the issue? If you have not yet solved the issue, kindly share any relevant debugging logs.

I don't have android development environment ready to test your code but I have confirmed the player works on webview using this old app https://github.com/chelovek84/mBrowser. 
![-2147483648_-211236](https://user-images.githubusercontent.com/25152892/180484795-95ca243a-d3c5-4fa2-b4ad-c8e6ddcc3cbc.jpg)


so probably the library links were broken if the webview works with other Javascript powered sites

**Comment by tuyensmartdev** [comment]
hi @mimidotsuser
I fixed it, but still have a problem in the first time, the video can't load thumbnail.
<img width="368" alt="Screen Shot 2022-08-01 at 23 45 38" src="https://user-images.githubusercontent.com/108281530/182201067-c30cd5dd-6481-456f-9939-50c8228f03b7.png">
Have you encountered this problem?

**Comment by mimidotsuser** [comment]
I didn't have any problem with video preview thumbnail. Check your debugging logs if all the links are working as expected.

**Comment by mimidotsuser** [comment]
closing this. 
Feel free to reopen the issue if still experiencing the H5P standalone related issues.
