### ISSUE TITLE
The "Send report" button disappears in the BOOK

### ISSUE THREAD

**Issue by getcher123** [tunapanda/h5p-standalone#134]
When viewing a book through h5p-standalone, the "Submit Report" button on the last screen disappears, which sends the results. 
![Screenshot_1](https://github.com/tunapanda/h5p-standalone/assets/60815740/9040dd44-2acb-4393-9a26-d64306eac0a0)
![Screenshot_3](https://github.com/tunapanda/h5p-standalone/assets/60815740/d11ee403-0111-4985-a0fa-57839e39803e)

**Comment by murageyun** [comment]
@getcher123 I didn't quite understand the problem.

Is the button missing altogether or the button disappears after results submission?

**Comment by getcher123** [comment]
The button is missing altogether. On the first screen I showed the button on h5p.com.

**Comment by getcher123** [comment]
@murageyun you could test this on https://3dfarm.ru/course

**Comment by murageyun** [comment]
I have seen the problem. The button has to be enabled via configuration which is not clearly documented here https://github.com/h5p/h5p-interactive-book/blob/786c11ca05bf10bfeddac345cecc1967f0a1171a/src/scripts/app.js#L58-L63

Here is a workaround until a fix is created,

```javascript
const el = document.getElementById('h5p-container');
const options = {
    h5pJsonPath: '/workspace/berries-28-441940',
    frameJs: 'https://unpkg.com/h5p-standalone/dist/frame.bundle.js',
    frameCss: 'https://unpkg.com/h5p-standalone/dist/styles/h5p.css',
    metadata: {
        title: "Book title here",
        license: "MIT"
    },

    preventH5PInit: true //prevent h5p player from initialization
}

new H5PStandalone.H5P(el, options)
    .then(() => {
        H5PIntegration.reportingIsEnabled = true; //this is the trick
        H5P.init(); //initialize the h5p player
    })

            
```

Summary of the fix:
- we are preventing the H5P player from initializing automatically (`preventH5PInit: true`)
- enabling the button 
- doing the H5P player initialization explicitly

**Comment by getcher123** [comment]
Thank you, this method works!

**Comment by 0xMurage** [comment]
fixed by https://github.com/tunapanda/h5p-standalone/pull/158
