### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'on')

### ISSUE THREAD

**Issue by BlackZero1122** [tunapanda/h5p-standalone#138]
Hello,

I.m using MAUI Blazor to run H5P. What i have done so far is make a function named play() in js like
`async function play() {
    try {
        const { H5P } = H5PStandalone || {};

        await new H5P(document.getElementById('h5p-container'), { h5pJsonPath: "h5p/contents/interactive_video", frameJs: 'h5p/assets/frame.bundle.js', frameCss: 'h5p/assets/styles/h5p.css' })
            .then(function () {
                // this is where you will listen for the xAPI event
                H5P.externalDispatcher.on('xAPI', (event) => {
                    // add your logic to send the event to the LRS  here.             
                    console.log('xAPI event: ', event); //(I am just logging to browser developer console for demo purpose)
                });
            });
    } catch (e) {
        console.log('error : ', e);
    }
}`
when i run this function it throws an error on H5P.externalDispatcher.on('xAPI', (event) => { line
error is ->
![Capture](https://github.com/tunapanda/h5p-standalone/assets/89926278/92b2fe65-d7e8-4887-b0c9-f2948e654a43)
Any idea why, How can i solve this

Thanks

**Comment by murageyun** [comment]
@BlackZero1122 does  MAUI Blazor  support [window](https://developer.mozilla.org/en-US/docs/Web/API/Window) object?

H5P was designed to run in a browser that supports the window.
https://github.com/tunapanda/h5p-standalone/blob/30e645e74bef178098f65e5990636926c899bfd4/vendor/h5p/js/h5p.js#L5

**Comment by BlackZero1122** [comment]
yes @murageyun, it has. the whole H5P project is running smoothly on it. only xAPI events are not triggered whenever user answer a question or submit the form.

**Comment by BlackZero1122** [comment]
i have. looked further into this and have logged both H5P and H5P.externalDispatcher. It turns out H5P.externalDispatcher Is not defined.

**Comment by BlackZero1122** [comment]
I have resolved the issue as, I believe as @murageyun said,

```
const { H5P } = window.H5P = H5PStandalone;

function initH5P(lesson) {
    new H5P(document.getElementById('h5p-container'), {
        h5pJsonPath: 'h5p/content/' + lesson,
        frameJs: 'h5p/frame.bundle.js',
        frameCss: 'h5p/styles/h5p.css'
    })
    .then(function () {
        // this is where you will listen for the xAPI event
        window.H5P?.externalDispatcher?.on('xAPI', (event) => {
            // add your logic to send the event to the LRS  here. 
            console.log('xAPI event: ', event); //(I am just logging to browser developer console for demo purpose)
        });
    });
}
```
Thanks!
