### ISSUE TITLE
Progressive Web App (PWA) Export

### ISSUE THREAD

**Issue by 90084** [tunapanda/h5p-standalone#141]
I'm using H5P to develop content for learners in developing countries. A huge segment of learners in the world (e.g. in emerging economies) have a low-spec'd device and internet access that is slow, patchy, and expensive. Progressive Web Apps (PWAs) have emerged as a very helpful approach to serve them. On the other hand, educators are always seeking to repurpose their educational content. Additionally, I've seen plenty of requests for 'offline viewing' of H5P resources or a 'player app'.

PWA export would help learners view H5P content offline and enable educators to distribute their content as a web app, independent of any CMS/LMS.

Below some resources I've used:
[Get started with Progressive Web Apps - Microsoft Edge Development | Microsoft Learn](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/)
[Progressive web apps (PWAs) | MDN](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps)
[Making PWAs work offline with Service workers - Progressive web apps (PWAs) | MDN](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers)

Thank you for your consideration.

**Comment by murageyun** [comment]
The player already has a built-in feature for exporting content. 
One can enable it by passing 
```javascript
 {
 export:true,
 downloadUrl: `your url to the zipped h5p content format`
 }
```

You can then utilize various browser API caching mechanisms to intelligently cache the assets and your static content.

I hope this resolves your issue.
