### ISSUE TITLE
RegEx for checking domains breaks spec and doesn't work for long domain names

### ISSUE THREAD

**Issue by gjsman** [tunapanda/h5p-standalone#160]
Hello,

`src/utils.ts` uses this RegEx to check for domain names:

```
const urlRegex = /^([a-z0-9]+:\/\/|www.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/i;
```

Careful observers might notice that it checks for gTLDs (.com, .org, etc.) by whether they are 2-6 characters long. This is possibly a typo, as the RFC for domain names says they can be between 2 and *63* characters long. Thus a more appropriate RegEx would be:

```
const urlRegex = /^([a-z0-9]+:\/\/|www.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,63}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/i;
```

This caused considerable debugging on my part when we switched to a domain with `.software` as the gTLD. Obviously too long, weird stuff happened. I'm filing an issue because, unfortunately, the package appears somewhat abandoned and more people might find this solution. I would personally recommend using the `patch-package` tool on `npm` to fix it without needing to fork.

**Comment by 0xMurage** [comment]
Thank you @gjsman  for bringing this issue to our attention and for your detailed explanation.

I will set aside some time to create a fix for this issue.

Thanks again for your contribution!

I will try to squeeze some time this month to also address other outstanding issues in the repository, contributions from anyone are always welcome.
