### ISSUE TITLE
It's not working on android webview 4.2.2, "ERR_UNKNOWN_URL_SCHEME"  about:blank

### ISSUE THREAD

**Issue by ShuiShengYe** [tunapanda/h5p-standalone#17]
I try to use H5P in my project. We use Android(4.2.2) webview to display h5p content. It can't load anything and get an error ERR_UNKNOWN_URL_SCHEME  "about:blank". I test it on Android(5.1.1),and get same error. But it's working on Android 7.

**Comment by pheraph** [comment]
You could test if your h5p content is displayed without `h5p-standalone` to find out if it's a problem with the standalone wrapper or h5p itself.

**Comment by Jakeii** [comment]
I don't think this is specific to h5p-standalone, but you may be able to use https://crosswalk-project.org/ to solve your problem.
