### ISSUE TITLE
Error in Documentation Tool When Exporting Text

### ISSUE THREAD

**Issue by mrjarbenne** [tunapanda/h5p-standalone#19]
When attempting to use the Export Text functionality within the Documentation Tool H5P Content type, a js error appears in the console, and the content export fails. 

![2018-02-18_17-14-10](https://user-images.githubusercontent.com/480667/36357675-585503b8-14cf-11e8-82a1-9118835d464b.png)

**Comment by Jakeii** [comment]
This is now fixed as of v2.0.0
