### ISSUE TITLE
add xapi statement gathering

### ISSUE THREAD

**Issue by Jakeii** [tunapanda/h5p-standalone#2]
Store these either in the browser in localstorage/indexdb or in android sqlite db for cordova.

**Comment by rhclayto** [comment]
Any progress on this?

**Comment by rhclayto** [comment]
I agree, I don't think this project needs to handle storing xAPI statements. Maybe a note in the documentation for those who haven't dealt with listening to xAPI statements before. I asked then promptly remembered having done this in a previous project (server-based rather than standalone h5p).

**Comment by shippeli** [comment]
Is it possible to pass an user ID to the library so that the xAPI events contain this user ID when firing events?
