### ISSUE TITLE
Bundled jQuery

### ISSUE THREAD

**Issue by rhclayto** [tunapanda/h5p-standalone#22]
Hi,

Will this work with a version of jQuery other than the one embedded in the script? It seems like a lot of extra weight if one already has jQuery present for other reasons.

**Comment by Jakeii** [comment]
Possibly, h5p only seems to support jQuery 1.x which is quite old. I'm not sure if it'd be worth it?

**Comment by rhclayto** [comment]
Yes, not worth it. Thanks for the answer.
