### ISSUE TITLE
doesn't render in IE

### ISSUE THREAD

**Issue by alrighty-then** [tunapanda/h5p-standalone#25]
Hi,

I love this - it will be really useful for what I'd like to do...

I can get this working fine in Chrome, Firefox etc. however not in IE, (specifically Edge)...

I've tried polyfills as suggested in a closed issue however I'm still not able to resolve this...
new error: Uncaught (in promise) TypeError: Object doesn't support property or method 'find'

My understanding is too limited to be able to resolve this alone so I would really appreciate some guidance if possible?

**Comment by Jakeii** [comment]
according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find Edge supports `Object.find`?

Used a polyfill for object.find to resolve your issue, e.g. https://github.com/jsPolyfill/Array.prototype.find

What requires you to support IE?

**Comment by alrighty-then** [comment]
Thanks for your reply...

I think my ignorance was causing the issue:
I've now added in _/npm/jspolyfill-array.prototype.find@0.1.3/find.min.js_ alongside _https://cdn.polyfill.io/v2/polyfill.min.js_ and it's now working - at least with my drag-and-drop test example.

My organisation uses IE as default browser and for me to be able to utilise this would depend on it working in IE.

Well it's working now anyway - 
Thank you kindly
