### ISSUE TITLE
Flickering in window

### ISSUE THREAD

**Issue by metaltwister** [tunapanda/h5p-standalone#27]
Hi. I'm facing a peculiar issue. Whenever I play the content the window/iframe starts flickering. Attached is the screen recording. 
Is there a way to solve this? It looks like the div is redrawing itself.
[https://anirudhamude.tinytake.com/sf/Mjk1ODgzN184ODc4Mjc4](url)

**Comment by shippeli** [comment]
If you can live with a permanently shown scrollbar apply the following style:

/* do not cut content but avoid video jittering */
html.h5p-iframe {
    overflow-y: scroll;
}

Overflow is set to hidden for the video container itself  and some ancestors. So i cannot explain where this problem comes from.

**Comment by Jakeii** [comment]
I hope @shippeli solved your issue!
