### ISSUE TITLE
medata and title

### ISSUE THREAD

**Issue by f5soh** [tunapanda/h5p-standalone#29]
Hi,
Currently testing standalone player with quizzes and presentation content.
Seems the medata is not retrieved correctly and title names are not displayed on slides (when 'Show title' is active) and summaries.
Drag and drop content titles are displayed with default "Drag and drop" title.

In H5P.DragQuestion-1.13/h5p-drag-question.js, for title in summaries :
```
o.prototype.getTitle = function() {
        return H5P.createTitle(this.contentData && this.contentData.metadata && this.contentData.metadata.title ? this.contentData.metadata.title : "Drag and drop")
    }
```
And slide content :
```
questionTitle: this.contentData && this.contentData.metadata && this.contentData.metadata.title ? this.contentData.metadata.title : "Drag and drop"
```

Laurent

**Comment by Jakeii** [comment]
Can you provide an example H5P?

**Comment by f5soh** [comment]
Online : http://technoargia.free.fr/h5p/

'Drag and Drop' on summary :
![summary](https://user-images.githubusercontent.com/10426169/68229227-24263700-fff7-11e9-833d-3c60082d562c.png)
H5P file :
[decouverte-du-mbot-6.zip](https://github.com/tunapanda/h5p-standalone/files/3810254/decouverte-du-mbot-6.zip)

**Comment by f5soh** [comment]
Ok, titles are fine now but i lost pictures...
Seems 2.0.0 try relative path (left window) and previous version show absolute path for pictures (right window).
![img_absolutepath](https://user-images.githubusercontent.com/10426169/68234147-ed551e80-0000-11ea-9800-3232bf307d31.png)

Not sure if i do the right way, sorry.

**Comment by f5soh** [comment]
Using latest Git clone and 'dist' symlink fixed the issue...

Thanks :+1:

**Comment by Jakeii** [comment]
Great!
