### ISSUE TITLE
Virtual Tour (360) not working

### ISSUE THREAD

**Issue by pheraph** [tunapanda/h5p-standalone#32]
I tried to provide the [360° example file](https://h5p.org/virtual-tour-360) with h5p standalone, but got the following error when viewing it:

`TypeError: this.mainLibrary.preloadedCss is undefined h5p-standalone-main.min.js:1:106590`

I suspect that this content type is not yet supported, right? Anyone have any idea what the problem is?

**Comment by sr258** [comment]
This is an issue that must be fixed in h5p-standalone. The virtual tour content type doesn't include a css file, but h5p-standalone expects one.

**Comment by shippeli** [comment]
I fixed this issue but ran into another problem: three.min.js:114 THREE.WebGLState: DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
Seems to be a bug in the required version of three.js, see https://stackoverflow.com/questions/24087757/three-js-and-loading-a-cross-domain-image
So i think a pull request does not make sense at the moment.

There are issues with other Libraries like latex (H5P.getLibraryConfig is not a function) an i guess the h5p-standalone is just out of sync with the latest h5p core libaries.

@Jakeii Will you or do you know someone who will update the h5p-standalone to work with the latest h5p api?

**Comment by Jakeii** [comment]
This is fixed in 2.0.2
