### ISSUE TITLE
full screen on ios

### ISSUE THREAD

**Issue by Ester-Korenevsky** [tunapanda/h5p-standalone#33]
I embedded an interactive video to my website, everything works fine on any device except the full screen button on iphones and ipads, when I click it nothing happens. 
Do you have an idea how to solve this problem?

**Comment by antoncazalet** [comment]
Hello,

If you're using an iframe, IOS block the fullscreen option.
But you can bypass the problem by using the `<div class"h5p-container">`.

**Comment by Jakeii** [comment]
Thanks @antoncazalet
