### ISSUE TITLE
Interactive Presentations with Dialog Cards (v1.7) are broken

### ISSUE THREAD

**Issue by pheraph** [tunapanda/h5p-standalone#34]
Currently Interactive Presentations with Dialog Cards (version 1.7 or higher) do not work anymore:

`TypeError: H5P.ConfirmationDialog is not a constructor. h5p-dialogcards.js:1:34901`

As a brute force method I replaced the file h5p-content/H5P.Dialogcards-1.7/dist/h5p-dialogcards.js with the [file version 1.6.2](https://github.com/h5p/h5p-dialogcards/releases/tag/1.6.2), which is about the same age as the last update of H5P Standalone. This seemed to solve the mentioned problem, but it might raise other problems.

It seems to be a growing problem that H5P is constantly evolving and H5P Standalone is stagnating and apparently no longer (?) maintained.

**Comment by Jakeii** [comment]
this has been fixed as of 2.0.1
