### ISSUE TITLE
Multiple embeds - second H5P affects the first

### ISSUE THREAD

**Issue by vladmz** [tunapanda/h5p-standalone#38]
When using the multiple embed setup() function the creation of a second H5P affects the first one. 

Specifically, if the first H5P is an image hotspot activity and is on its own it works fine, however, if another H5P is added, the background image from the first not longer displays. 

Inspection reveals that the image src references the folder of the second H5P not the first as it should. If the order of the two in the setup() function is reversed the problem disappears.

The attached file illustrates the problem.
[issue-example.txt](https://github.com/tunapanda/h5p-standalone/files/4335451/issue-example.txt)

**Comment by mimidotsuser** [comment]
Hello @vladmz, are you still experiencing this issue? I couldn't replicate your issue.  If you are using a custom H5P, kindly verify the `content.json` has the correct images path.

I have used the greeting card example https://h5p.org/node/885 and image hotspot example  https://h5p.org/image-hotspots. 

The images are all loaded correctly as below.
 
![Screenshot from 2021-04-14 18-03-22](https://user-images.githubusercontent.com/25152892/114734390-d580de80-9d4c-11eb-994b-d41909ee2abf.png)

Interchanging the order of how the H5P renders them has no effect

![Screenshot from 2021-04-14 18-16-40](https://user-images.githubusercontent.com/25152892/114735191-9bfca300-9d4d-11eb-98d1-2cf4c49815bd.png)

**Comment by mimidotsuser** [comment]
feel free to reopen the issue if suggested solution doesn't work
