### ISSUE TITLE
librariesPath ignored

### ISSUE THREAD

**Issue by briankalbster** [tunapanda/h5p-standalone#40]
Great project. Thank you.

I am having an issue with the librariesPath.  I move my libraries to a separate directory in my project, and then pass the librariesPath into the H5P function. However, when the h5P standalone loads, it is still trying to load the libraries from the local content path.  Is there a certain format the library file structure needs to be in for this to accept my library path?

my libraries are in /h5p/libraries

for example /h5p/libraries/H5P.Video-1.5
but it is trying to load from '/h5p_packages/base'

below is my example code. 

`
        const options = {
           // Optional unique ID, by default will be randomly generated
          frameJs: '/js/frame.bundle.js',
          frameCss: '/css/h5p.css'
        };

        const displayOptions = { // Customise the look of the H5P
            frame: false,
            copyright: true,
            embed: false,
            download: false,
            icon: true,
            export: false
          };

        const librariesPath = "/h5p/libraries";
        const h5pLocation = '/h5p_packages/base';
        const el = document.getElementById('h5p-container'); //,librariesPath
        const h5p = await new H5P(el, h5pLocation, options,displayOptions,librariesPath);`

**Comment by ralokt** [comment]
Same here. Am bypassing this issue with a symlink for now.

**Comment by benabel** [comment]
It seems that the bundle haven't been build since the librairiePth addition, if your running the example from the test repo, you need before to build it with:

    npm run build

Also it seems that this change have not been published to npm trying to include it from unpkg:
```html
 <script type="text/javascript" src="https://unpkg.com/h5p-standalone/dist/main.bundle.js"></script>
```
