### ISSUE TITLE
`H5P.getLibraryPath(<lib>)` returns `"undefined/<...>"`

### ISSUE THREAD

**Issue by ralokt** [tunapanda/h5p-standalone#43]
When running a H5P using the new `librariesPath` parameter that needs to call `H5P.getLibraryPath(<lib>)` (for example to load assets) that call returns `"undefined/<...>"`.

`This.librariesPath = <path>` is correctly written to the console, however, and everything else runs correctly, except for the fact that assets aren't loaded because the path is wrong.

Also, when I don't specify a `librariesPath`, I immediately get `This.librariesPath = [object Object]` written to the console, and the main H5P library isn't even loaded because it tries to load `/[object%20Object]/<lib>/library.json`.

This happens when I build from current master (85c11382a84dd17989a252f427ecc56c1c0c82be), which appears to be the correct version for 2.1.1 if I'm parsing the commit history correctly.

**Comment by ralokt** [comment]
I believe I have found the root of the second problem: https://github.com/tunapanda/h5p-standalone/blob/85c11382a84dd17989a252f427ecc56c1c0c82be/src/js/h5p-standalone.class.js#L11

This will be `false` if no `librariesPath` is passed, so in the `else` block, `librariesPath` will be set to `{}`.

**Comment by Jakeii** [comment]
Seems I wasn't paying attention for the last PR, this should be fixed now, and tagged in 2.1.2. Also have setup CI to hopefully catch this sort of thing...

**Comment by ralokt** [comment]
Thanks for the fast response!

The main problem (`H5P.getLibraryPath(<lib>)`) is still there, though. From what I can tell, https://github.com/tunapanda/h5p-standalone/blob/b0cb1aaf17b8051e3d39bb22f15a81f343f59753/src/js/frame.js#L10 this code is new. I'm guessing that something here isn't working properly - what I can tell from taking a brief look is that `this.librariesPath` is not set at all when it executes. Perhaps something that happens when the frame is created?

**Comment by ralokt** [comment]
I created a pull request (#44). It passes tests locally, and also fixes the issue I am having. I also included the new bundles already.

**Comment by Jakeii** [comment]
Hmm I can't seem to reproduce, are you able to include the H5P where the issue happens?

**Comment by ralokt** [comment]
I created a minimal reproducible example.

Complete, built webdir ready to be served locally:
[getlibpath-minimal.zip](https://github.com/tunapanda/h5p-standalone/files/4695274/getlibpath-minimal.zip)
H5P package:
[getlibpath-minimal.h5p.zip](https://github.com/tunapanda/h5p-standalone/files/4695277/getlibpath-minimal.h5p.zip)
(Note: I added an extra zip extension because GitHub didn't allow me to upload it with the h5p extension)
(Note: This was created with `h5p pack` and doesn't contain the `h5p.json` - it's included in the built bundle, though.)

**Comment by ralokt** [comment]
Completely forgot the instructions to reproduce, sorry.

 * extract `getlibpath-minimal.zip`
 * change into the newly created `_build` directory
 * start a HTTP server that serves this directory (fE `python -m http.server`)
 * navigate to `http://localhost:8000/index.html` (or whatever port the local server is listening on)
 * open the console
 * observe the output.
    * expected: `h5p/libraries/H5P.GetlibpathMinimal-0.1`
    * actual: `undefined/H5P.GetlibpathMinimal-0.1`

**Comment by ralokt** [comment]
Ah yes, that's a lot cleaner than just fixing the hack, of course. You're welcome!

Also I can confirm that it works now - thanks a lot!
