### ISSUE TITLE
Build system is broken

### ISSUE THREAD

**Issue by mikedawson** [tunapanda/h5p-standalone#53]
It seems like the build system is broken here. The pre-built files in dist work. However if one does a normal build, e.g.

Steps to reproduce:
```
$ git clone git@github.com:tunapanda/h5p-standalone.git
$ cd h5p-standalone
$ npm install
$ npm install --dev
$ npm run build
$ npm run test
```

It will build the Javascript into dist, but then all tests fail with the following error:
```
  > Cannot assign to read only property 'exports' of object '#<Object>'
```

It also produces the following warning when being built:

```
WARNING in ./src/js/h5p-standalone.class.js 117:16-19
"export 'default' (imported as 'H5P') was not found in 'imports-loader?H5PIntegration=>window.H5PIntegration!H5P'
 @ ./src/js/index.js

WARNING in ./src/js/frame.js 9:15-18
"export 'default' (imported as 'H5P') was not found in 'imports-loader?H5PIntegration=>window.parent.H5PIntegration!H5P
```

**Comment by Jakeii** [comment]
this project uses yarn, it's important to use the right one for the project as yarn.lock or package-lock.json is used to lock versions.
