### ISSUE TITLE
Absolute path broken

### ISSUE THREAD

**Issue by 7Ds7** [tunapanda/h5p-standalone#56]
Not sure what was the intention with this [changes]( https://github.com/tunapanda/h5p-standalone/commit/03bdbb2d06a18f2f9151863cda1b3a7112101741#diff-14f080ce299405b0c6867e944a43df649cfde781300576c95f320c30a8f609dfR6)

But those broke the assets of a h5p if we pass one absolute url (with protocol)

ex:
if we pass a url like `http://domain.com/h5p-test` it returns `http://current-domain.com/http://domain.com/h5p-test` while getting the h5p assets

**Comment by sjewo** [comment]
`urlPath(file)` will also add the full page url in front of the h5pLocation path if it is a relative url.

For example the relative path `images/file-5d9c71c122968.PNG` becomes `http://domain/path_of_the_webpage//hp5-standandalon/h5pLocation/content/images/file-5d9c71c122968.PNG`. 

This results in broken image links for my test h5p files.

**Comment by tdxdave** [comment]
I got this as well, looks like images are broken we part of content.
