### ISSUE TITLE
Flickering scrollbar in Chrome.

### ISSUE THREAD

**Issue by bobvanvliet** [tunapanda/h5p-standalone#62]
In Chrome, the vertical scrollbar in the iframe flickers on and off.

At least it did for me with an interactive video, and others have similar issues elsewhere. See [this forum post](https://h5p.org/node/1117083) on h5p.org.

That post and its first comment also point out the fix: the h5p iframe should have `scrolling="no"`.

I hacked this into my `main.bundje.js` and this fixes the problem.

I don't have the expertise to fix this properly in the source and create a pull request, but I think where I inserted it corresponds to line 42 in `src/js/h5p-standalone.class.js` (I found the correct place by [searching](https://github.com/tunapanda/h5p-standalone/search?q=frameborder) the h5p-standalone code for where `frameBorder="0"` is set).

**Comment by mimidotsuser** [comment]
@bobvanvliet thank you for raising the issue. We are providing a fix on latest updates

**Comment by bobvanvliet** [comment]
OK, great! This big makes embeds pretty much unusable in Chrome. Hopefully my hack helps those who, like myself, have a course starting next week and cannot wait for updates ;-)
