### ISSUE TITLE
Activity id does not seem to be passed to xAPI events

### ISSUE THREAD

**Issue by mrik974** [tunapanda/h5p-standalone#78]
Hi there ! I'm using your lib to display multiple H5P activities in a single page.
Each activity has an `id` set.
I'm also using `H5P.externalDispatcher` to track on xAPI events. 
It works, every activity displayed sends events that are caught and forwarded by the dispatcher.
But every event I receive looks like this (note the ` object.id ` field ) : 

<img width="612" alt="Screenshot 2021-04-25 at 21 06 22" src="https://user-images.githubusercontent.com/16136210/116006094-1c52bc00-a60a-11eb-9cb5-2ee86aa5b764.png">

I've tried multiple kinds of id, even an URI (which, by the way, is a xAPI requirement).

I don't know what to do, I need this id to correctly handle the events. Do you have a solution, or a workaround ? 

Edit : Here's the iframe code for the first activity, the `content-id` field is set to `undefined`.
```
<iframe id="h5p-iframe-undefined" class="h5p-iframe h5p-initialized" scrolling="no" data-content-id="undefined" style="width: 100%; height: 205px; border: medium none; display: block;" src="about:blank" frameborder="0"></iframe>
```
 
Have a good day,

Emeric

**Comment by mrik974** [comment]
Hi there. I tried a few things and I've found out that the minified version (or even the js file) of the lib does not contain any reference to the `options.id` field. I mean in your "h5p-standalone.class.ts" there's this line : 
`    this.id = options.id || Math.random().toString(36).substr(2, 9);
`
But I can't find any reference of it in the js file nor in the minified file. When I manually add this to the `main.bundle.js` (I know it's bad practice, I just want to try a few things out without having to rebuild the lib), it works and the H5P activity has an id :  
`n.id ? (this.id = p(n.id)) : (n.id = Math.random().toString(36).substr(2, 9)),`
Here's the result in the DOM after I added this : 
<img width="617" alt="Screenshot 2021-04-26 at 14 50 28" src="https://user-images.githubusercontent.com/16136210/116085092-c0864280-a69e-11eb-9fda-d408c3df566c.png">

But, it doesn't end here. Even though the ID is now set, the xAPI events do not use it at all and I still have an `undefined` field.

**Comment by kileha3** [comment]
Hi @mrik974, I think this issue was addressed on pull request #52 but unfortunately, it wasn't merged into master. I will try merging the latest master so that later can be merged into master.

**Comment by kileha3** [comment]
Activity ID was being passed as one of query params to the URL, something like this:-
http://localhost:8080/ContainerMount/177892100433350656/index.html?actor={"account":{"homePage":"http://localhost:8080/","name":"John Doe"}}&endpoint=http://localhost:8080/xapi/13112/&auth=OjFjMGY4NTYxNzUwOGI4YWY0NjFkNzU5MWUxMzE1ZGQ1&registration=a1045a8f-474b-4e58-aae3-fad297dd3632&activity_id=http://localhost:8080/177892100433350656/3196e3e6-6f56-457c-95ef-882b734ac96d

**Comment by mrik974** [comment]
Hi @kileha3 thank you for your answer, but I don't think I have the same issue. 
The present commit shows an object called `registration` being modified, but I believe my matter is more about the `activityId` object. 
Also I am not trying to send the xAPI event through the H5P lib, I'm only trying to catch them. And finally the `activityId` in the file `vendor/h5p/js/h5p.js` seems to be stored within the global `H5P` variable, which doesn't seem good in my use case where I have multiple activities displayed in the same screen. It showed me a lead to follow though, I'll try to see where the event is generated in the H5P vendor lib.

**Comment by mrik974** [comment]
I haven't found out what's going on but what I've found out is the h5p event has an `object.definition.extensions` field that contains the id. I think it's really more a matter of vendor lib then, so I won't bother you with it. 
But I also think you have a line missing in your `h5p-standalone.class.js` which I think is transpiled from the `h5p-standalone.class.ts` (in which the line isn't missing) and this line is `this.id = options.id || Math.random().toString(36).substr(2, 9);` in the constructor.
