### ISSUE TITLE
Object id undefined when sending xapi

### ISSUE THREAD

**Issue by sloopint** [tunapanda/h5p-standalone#84]
Hello,
I try to send xapi data to my LRS. But I can’t find the way to achieve that. It seems I have the same issue as mrik974 (post #78, closed). The process is interrupted because Object id is undefined. I think it prevents me from sending statements: the web console displays a 400 error. Am I doing something wrong or is it a bug?
Thank you very much for your help.
And thanks again for this fantastic tool!
![Capture d’écran 2021-06-07 à 14 03 07](https://user-images.githubusercontent.com/55651117/121014515-5d59f680-c79a-11eb-88fd-608eecc242aa.png)

**Comment by mimidotsuser** [comment]
@sloopint thank you for this. 
I was able to replicate the issue.
 A `url` property is expected on H5P content object and this is not done at the moment.
https://github.com/tunapanda/h5p-standalone/blob/94b79fb5832691e94835051117aa73673cc3044a/src/js/h5p-standalone.class.js#L137

 I will create a fix for this.

**Comment by mimidotsuser** [comment]
The identifier can be overridden by providing `xAPIObjectIRI` parameter when initializing H5P Standalone i.e.

```js
  const el = document.getElementById("h5p-container");
  const options = {
    h5pJsonPath: "/h5p-folder",
    frameJs: "/assets/frame.bundle.js",
    frameCss: "/assets/styles/h5p.css",
    xAPIObjectIRI: "http://example.com/activities/problem-solving" //replace with any valid Activity id 
  };

new H5PStandalone.H5P(el, options).then(function () {
  H5P.externalDispatcher.on("xAPI", (event) => {
    //do something useful with the event
    console.log("xAPI event data ", event.data);
  });
});
```
