### ISSUE TITLE
Fullscreen button not showing on Virtual Tour

### ISSUE THREAD

**Issue by edubox-rpi** [tunapanda/h5p-standalone#85]
On the official demo from Joubel (https://h5p.org/virtual-tour-360), there is a fullscreen button at the top right of the scene.
This button is not showing when loading the same content with h5p-standalone.
Any idea how to make it visible?
Thanks for your great work!

**Comment by mimidotsuser** [comment]
Thank you @edubox-rpi. Seems the full-screen property is set to default at the moment. 
I will expose the property so anyone can configure the behavior

**Comment by mimidotsuser** [comment]
@edubox-rpi you can now enable the button by adding the fullScreen option i.e.


```
const el = document.getElementById('h5p-container');
const options = {
  h5pJsonPath:  '/h5p-folder',
  frameJs: '/assets/frame.bundle.js',
  frameCss: '/assets/styles/h5p.css',
  fullScreen: true
}

new H5PStandalone.H5P(el, options);
```

**Comment by edubox-rpi** [comment]
Thanks, it works!
But, when I exit fullscreen and go fullscreen again, the button is not hidden and it throws an error in the console.

**Comment by mimidotsuser** [comment]
@edubox-rpi I have raised an issue on H5P forums and hope will get feedback to determine if we will provide a hack or a permanent fix for the issue.

A quick fix would be assgining this event callback function a name
https://github.com/tunapanda/h5p-standalone/blob/ecbcf2aef57f512b381f1bc0a56dd8dadf3222f4/vendor/h5p/js/h5p.js#L676

and then replacing `arguments.callee` with above function name
https://github.com/tunapanda/h5p-standalone/blob/ecbcf2aef57f512b381f1bc0a56dd8dadf3222f4/vendor/h5p/js/h5p.js#L686

then build the standalone player using `yarn build`

i.e.

```js
document.addEventListener(eventName, function fullscreenEvtHandler() {
    if (first === undefined) {
        // We are entering fullscreen mode
        first = false;
        entered();
        return;
    }

    // We are exiting fullscreen
    done('h5p-fullscreen');
    document.removeEventListener(eventName, fullscreenEvtHandler, false);
});
```
