### ISSUE TITLE
Provide full H5P experience

### ISSUE THREAD

**Issue by murageyun** [tunapanda/h5p-standalone#89]
Although H5P standalone provides an easy and quick way for a developer/less technical user to display any H5P content on a website, few configuration options are currently not exposed for customization.
 Below configurations options need to be exposed to improve the standalone benefits similar to other H5P platform integration options:

1) General H5P player/editor settings (Under H5PIntegration)

 **Property**         |  **Purpose**
------------|--------------------|
~~`ajax.setFinished`~~| ~~Where to post user results once they complete. [Ref](https://github.com/h5p/h5p-php-library/blob/4599291d7ce0cfb90edd188b181416f31514748e/js/h5p.js#L2209)~~|
~~`ajax.contentUserData`~~ | ~~Where to post user progress/content state. [Ref](https://github.com/h5p/h5p-php-library/blob/4599291d7ce0cfb90edd188b181416f31514748e/js/h5p.js#L2346)~~ |
~~`postUserStatistics`~~ | ~~Indicates if user results should be sent to `ajax.setFinished` url. [Ref](https://github.com/h5p/h5p-php-library/blob/4599291d7ce0cfb90edd188b181416f31514748e/js/h5p.js#L2188)~~|
| | |
~~`user.name`~~ | ~~Current user name  (_if available_). [Ref](https://github.com/h5p/h5p-php-library/blob/4599291d7ce0cfb90edd188b181416f31514748e/js/h5p-x-api-event.js#L195)~~|
~~`user.email`~~ | ~~Current user email (_if available_)~~ |
`siteUrl`    | User bio url  (_if available_) - used to identify the `actor` if `user.*` is not provided. [Ref](https://github.com/h5p/h5p-php-library/blob/4599291d7ce0cfb90edd188b181416f31514748e/js/h5p-x-api-event.js#L219)|
~~`saveFreq`~~ | ~~How often current user engagement content state should be saved (in seconds). false to disable [Ref](https://github.com/h5p/h5p-php-library/blob/4599291d7ce0cfb90edd188b181416f31514748e/js/h5p.js#L2843).~~|
`l10n.h5p` | H5P core JS components  localization namespace. [Ref](https://github.com/h5p/h5p-php-library/blob/4599291d7ce0cfb90edd188b181416f31514748e/js/h5p.js#L1011)|
~~`url`~~ | ~~Used to generate content url if `H5PIntegration.contents[contentId].contentUrl` is not available. [Ref](https://github.com/h5p/h5p-php-library/blob/4599291d7ce0cfb90edd188b181416f31514748e/js/h5p.js#L818).~~ |

2) Content specific properties: (Under H5PIntegration.contents[contentId])
 
 **Property** |  **Purpose**
 ------------ | ------------------
 ~~`contentUserData`~~ | ~~Content state/user data according to interaction with the content. [Ref](https://github.com/h5p/h5p-php-library/blob/4599291d7ce0cfb90edd188b181416f31514748e/js/h5p.js#L2402)~~|
~~`embedCode`~~ | ~~HTML code that can be used to embed the content on other web media. [Ref](https://github.com/h5p/h5p-php-library/blob/4599291d7ce0cfb90edd188b181416f31514748e/js/h5p.js#L1350)~~|

**Comment by LyesJeu** [comment]
Hi, is there possibility to find old version of H5P Standalone, because with this version, any thing work !?
Thanks

**Comment by mimidotsuser** [comment]
@LyesJeu you can find all the releases on https://github.com/tunapanda/h5p-standalone/releases or on NPM https://www.npmjs.com/package/h5p-standalone
