### ISSUE TITLE
Implementation in Lumi - Step 6

### ISSUE THREAD

**Issue by Busserl** [tunapanda/h5p-standalone#99]
Hey,

I am having some problems with the implementation in Lumi. 
I followed the "Direct use" installation and everything worked until step 6. 

So I tried to implement the code into Lumi but I am getting the following errors:
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)
"Uncaught (in promise)"
"Uncaught TypeError: Cannot read properties of null (reading 'H5P')"

I don´t know how to fix it and I couldn´t find a solution to this. 

Did someone encounter a similar problem and might be able to help me?

Thanks in advance! 

Kind regards

**Comment by sr258** [comment]
Lumi dev here. I'm not sure what you're trying to do. Why mix Lumi and h5p-standalone at all?

**Comment by Busserl** [comment]
Thanks for your reply! 
When I downloaded Lumi, it couldn´t connect to the content types at all.  
I searched around the web and found an article about the H5P-standalone and the link guiding me to this page. 
I followed the instructions and it connected to the content types, but it had some problems as mentioned above. 

Well, that´s basically it. I just tried to make it work somehow.

**Comment by sr258** [comment]
The connection error should be resolved. Try it again with lumi. h5p-standalone if for deployments of content on servers only.

**Comment by mimidotsuser** [comment]
closing this as it's related to LUMI. 
Kindly feel free to re-open the issue if still facing the H5P-standalone related problems.
